package com.megazone.ERPSystem_phase3_FinanceHR.hr.repository.basic_information_management.EmployeeImage;

public class EmployeeImageRepositoryCustomImpl implements EmployeeImageRepositoryCustom {

}
